name: Build an apk and push it

on:
  push:
    branches:
      - main
      - build-github-action

jobs:
  build:
    defaults:
      run:
        working-directory: PyroApp
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease --no-daemon
      - name: List files
        run: |
          ls -R android/
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: ./PyroApp/android/app/build/outputs/apk/debug/app-release.apk
          retention-days: 30
